Added stdout log file to validation output

diff --git a/.github/workflows/ci_java_validation.yml b/.github/workflows/ci_java_validation.yml
--- a/.github/workflows/ci_java_validation.yml
+++ b/.github/workflows/ci_java_validation.yml
@@ -179,9 +179,9 @@ jobs:
           NC=$'\033[0m'
                 
           if $INPUT_JAVA_VALIDATION_ENABLED; then
-            echo "Starting validation using Java validator ..."
+            echo "Starting validation using Java validator ..." | tee validation-stdout.log
             IG_DEPENDENCIES=$(jq -r '(.dependencies) | to_entries | map("-ig " + .key + "#" + .value) | join(" ")' package.json)
-            echo "IG_DEPENDENCIES: $IG_DEPENDENCIES"
+            echo "IG_DEPENDENCIES: $IG_DEPENDENCIES" | tee -a validation-stdout.log
             
             for p in $INPUT_PATH_TO_CONFORMANCE_RESOURCES; # Get combined path to conformance resources, we want to provide all other directories as context for the current validation
             do  
@@ -196,10 +196,15 @@ jobs:
                 p="$p/"
               fi
               
+              echo "Validating path: $p" | tee -a validation-stdout.log
+
               UNESCPAED_IG_DEPENDENCIES=$(echo $IG_DEPENDENCIES | tr -d '"')
               
-              javaValidatorOutput=$(java -jar validator_cli.jar $GITHUB_WORKSPACE/$p*.xml $GITHUB_WORKSPACE/$p*.json -version $FHIR_VERSION $INPUT_JAVA_VALIDATION_OPTIONS $UNESCPAED_IG_DEPENDENCIES $LOCAL_IG_PARAMETERS -tx http://127.0.0.1:8090/fhir || true)
-  
+              javaValidatorOutput=$(java -jar validator_cli.jar $GITHUB_WORKSPACE/$p*.xml $GITHUB_WORKSPACE/$p*.json -version $FHIR_VERSION $INPUT_JAVA_VALIDATION_OPTIONS $UNESCPAED_IG_DEPENDENCIES $LOCAL_IG_PARAMETERS -tx http://127.0.0.1:8090/fhir 2>&1 || true)
+
+              # Save raw output to file
+              echo "$javaValidatorOutput" >> validation-stdout.log
+
               javaValidatorOutput=$(echo "$javaValidatorOutput" | sed -E "
                 s/(:[[:space:]]*)Error([[:space:]]+-)/\1${ERROR}Error${NC}\2/g;
                 s/(:[[:space:]]*)Warning([[:space:]]+-)/\1${WARN}Warning${NC}\2/g;
@@ -216,13 +221,13 @@ jobs:
               echo -e "$javaValidatorOutput"
 
               if echo "$javaValidatorOutput" | grep -F "*FAILURE*" > /dev/null; then
-                echo "Validation failed with errors. Check the logs for more details."
+                echo "Validation failed with errors. Check the logs for more details." | tee -a validation-stdout.log
                 exit 1
               fi
               
             done
           fi
-          echo "Finished validation using Java validator ..."
+          echo "Finished validation using Java validator ..." | tee -a validation-stdout.log
         shell: bash
         env:
           FHIR_VERSION: "4.0"
@@ -239,5 +244,5 @@ jobs:
             ${{ inputs.working-directory }}/txlog.html
             ${{ inputs.working-directory }}/validation.html
             ${{ inputs.working-directory }}/validation.json
+            ${{ inputs.working-directory }}/validation-stdout.log
 
-    
